### ISSUE TITLE
What are the 14 monitoring stations?

### ISSUE THREAD

**Issue by joethorley** [bcgov/water-quality-analysis#1]

**Comment by joethorley** [comment]
Is there a way I can easily figure them out?

**Comment by joethorley** [comment]
From csv

```
stations <- read_csv("data/BC_WQI_Appendix_2016.csv")
```

**Comment by stephhazlitt** [comment]
The 14 monitoring stations are listed in the Schedule A – Appendix table, including EMS ID and Station Number and deliverables per station.
