### ISSUE TITLE
What are the EMS codes for  'NO2/NO3', 'NO2+NO3'?

### ISSUE THREAD

**Issue by joethorley** [bcgov/water-quality-analysis#10]

**Comment by stephhazlitt** [comment]
I found NO2 + NO3 in the dict-num.xls file available in the [EMS metadata record in the BC Data Catalogue](https://catalogue.data.gov.bc.ca/dataset/bc-environmental-monitoring-system-results). Parameter Code: 0110

**Comment by joethorley** [comment]
Isn't 0110 just = `Nitrogen NO3 Total`
I can get N02 and N03 separately - I just don't know what both together are or divided by each other

**Comment by stephhazlitt** [comment]
Sorry, that should have been 0109: Nitrogen NO2 + NO3. I am still working on finding NO2/NO3.

**Comment by ateucher** [comment]
There is also `Nitrate(NO3) + Nitrite(NO2) Dissolved`, which is parameter code `1109`

**Comment by joethorley** [comment]
Currently I have

```
Nitrate Dissolved,EMS_1110,mg/L,mean
Nitrate Soluble,EMS_NO3_,mg/L,mean
Nitrate Total,EMS_0110,mg/L,mean
Nitrate Nitrite,EMS_0109,mg/L,mean
Nitrite Dissolved,EMS_0111,mg/L,mean
Nitrogen Dissolved,EMS_1114,mg/L,mean
Nitrogen Total,EMS_0114,mg/L,mean
```

I'm thinking I should rename `Nitrate Nitrate` as `Nitrate Nitrite Total` and add

```
Nitrate Nitrite Dissolved,EMS_1109,mg/L,mean
```

**Comment by ateucher** [comment]
To get the full suite of possible parameters with codes, can you just use rems and pull out all unique combinations of PARAMETER and PARAMETER_CODE?

Why do you need to rename them?

**Comment by stephhazlitt** [comment]
For interpreting the report with parameter recommendations per station: NO2/NO3 == NO2 + NO3

**Comment by joethorley** [comment]
@ateucher I've done that and have included it in wqbc. However the EMS naming scheme is inconsistent. To make the names easier to guess and easier to interpret and process by a computer we introduced a new naming scheme in wqbc. The names do of course link to the EMS codes so are unambiguous in that sense (and can therefore be linked to the EMS PARAMETER names). The real problem is people using names without linking them to EMS codes.

**Comment by joethorley** [comment]
@stephhazlitt After a peruse of the report I concur with your conclusion that NO2/NO3 == NO2 + NO3 (does this mean that NO2 and N03 are both 0.5 ;)). I'm closing the thread as the question has been answered.

**Comment by joethorley** [comment]
Actually I'm reopening as I need to resolve Nitrate Nitrite and

```
Nitrate Nitrite Dissolved,EMS_1109,mg/L,mean
```
