### ISSUE TITLE
What are the start and end years for the trend analysis?

### ISSUE THREAD

**Issue by joethorley** [bcgov/water-quality-analysis#3]

**Comment by joethorley** [comment]
Trend analyses should end at 2015 and start at the earliest year for which there is sufficient data for each station. I believe 10 years is considered the minimum number of years required, although I would give it a go for 7-8 just to see.

**Comment by stephhazlitt** [comment]
Trend analyses should end at 2015 and start at the earliest year for which there is sufficient data for each station. I believe 10 years is considered the minimum number of years required, although I would give it a go for 7-8 just to see.
