### ISSUE TITLE
Is "x Dissolved" the same as "x-Soluble" in ems?

### ISSUE THREAD

**Issue by joethorley** [bcgov/water-quality-analysis#6]
For example

```
[913] "Zinc Dissolved"                                              
[914] "Zinc Total"                                                  
[915] "Zinc-Extractable"                                            
[916] "Zinc-Insoluble"                                              
[917] "Zinc-Soluble" 
```

**Comment by stephhazlitt** [comment]
@HeatherGranger do you know the answer to this question?

**Comment by HeatherGranger** [comment]
In looking at the lab test description, I would go with yes, they are the same. Just to be sure though, I would check with Joyce Austin, our lab manager. I'm not sure why there would be both options and I'm not sure if soluble and dissolved data should be grouped together.

**Comment by joethorley** [comment]
@HeatherGranger What was the final answer here. I'm thinking that dissolved is that which is dissolved while soluble is that which could be dissolved. They could therefore vary in principle.

**Comment by HeatherGranger** [comment]
I've sent an email out to check so let you know when I hear back. I know they differ in scientific explanation, but not sure how we treat them in water quality analysis / how they're measured and put into EMS.

**Comment by joethorley** [comment]
@HeatherGranger - thanks - I appreciate it

**Comment by joethorley** [comment]
Closed - concluded they do differ
