### ISSUE TITLE
We don't currently have limits for lots of parameters

### ISSUE THREAD

**Issue by joethorley** [bcgov/water-quality-analysis#7]
'Ammonia', 'Barium', 'Chromium', 'Colour', 'Copper Dissolved', 'Cyanide', 'E. coli', 'Fecal coliforms', 'Nickel', 'Nitrogen Total Dissolved', 'NO2/NO3', 'NO2+NO3', 'Oxygen Dissolved', 'Phosphorus Total', 'Phosphorus Total Dissolved', 'Temperature', 'Thallium' and 'Turbidity'.

**Comment by joethorley** [comment]
The Canada and Environment Canada 2014 reports

> British Columbia
> Parameter
> Form
> Guideline

Source
Alkalinity
20 mg [CaCO3]/L
a
Arsenic
total
5 μg/L
b
Cadmium
total
10(86log10[hardness]-3.2 μg/L) for hardness > 50 mg
[CaCO3]/L0.019 μg/L for hardness < 50 mg [CaCO3]/L
SSG1 (certain sites)
b c
Chloride
total dissolved
120 mg/L
b
Chromium
total
SSG1
a c e f g j i l m
Copper
total
2 μg/L for hardness < 90 mg [CaCO3]/L 0.2e0.8545_ln[hardness]-1.465_ for hardness

> 90 mg [CaCO3]/L
> where hardness as mg [CaCO3]/L SSG1
> d e j l m n
> Cyanide
> weak acid dissociable
> 5 μg/L
> b
> Fluoride
> total
> 0.3 mg/L (BC08NM001), 0.35 mg/L (BC08NN0021)
> o
> Iron
> total
> 0.3 mg/L
> d
> Lead
> total
> 1 ug/L when hardness < 50 mg [CaCO3]/L, e1.273_ln[hardness]-4.705 μg/L
> when hardness < 50 mg [CaCO3]/L SSG1
> d p
> Manganese
> total dissolved
> SSG1
> k q
> Molybdenum
> total
> 73 ug/L
> b r
> Nickel
> total
> e0.76_ln[hardness]+1.06 μg/L
> d
> Nitrate
> total dissolved
> 2.93 mg N/L
> d
> Nitrite
> total
> 0.02 mg N/L
> s
> Nitrogen
> total, total dissolved
> 0.7 mg/L
> s
> Oxygen
> dissolved
> SSG1
> b t u
> Canadian Environmental Sustainability Indicators Page 17 of 32
>    Parameter
>          Form
>           Guideline
>          Source
>          pH
>   SSG1
> b c m t
>     Phosphorus
>   total and total dissolved
>    0.025 mg/L
>      d v
>   Selenium
>    total dissolved
>      2 μg/L
>     d w
>       Silver
>   total
> 0.05 μg/L for hardness < 100 mg [CaCO3]/L 1.9 μg/L for hardness > 100 mg [CaCO3]/L where hardness as mg [CaCO3]/L
> SSG1
>   d x
>   Sulphate
>     dissolved
>  50 mg/L
>      y
>   Temperature
>      SSG1
>      z
>   Thallium
>      total
>    0.8 μg/L
>       b
>     Uranium
>    total
>   10 μg/L
>    a
>     Zinc
>    total
>   7.5 μg/L
>  c e j k aa
>      1 SSG denotes that different site-specific guidelines or formulas were used at sites. For details on the derivation of site- specific guidelines, consult BCMOE (1997). ab
> British Columbia Water Quality Guideline Sources:
> a British Columbia Ministry of Environment (2006) A compendium of working water quality guidelines for British Columbia. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/working.html.
> b Canadian Council of Ministers of the Environment (2007) Canadian Water Quality Guidelines for the Protection of Aquatic Life: Summary table, Update 7.1. Retrieved on 17 December, 2013. Available from: http://st-ts.ccme.ca/.
> c Butcher GA (1992) Lower Columbia River, Hugh Keeleyside dam to Birchbank water quality assessment and objectives: Technical appendix. British Columbia Ministry of the Environment, Lands and Parks. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/objectives/lowcolum/Keenleysidetech.pdf.
> d Government of Canada (2008) Technical guidance document for water quality index practitioners reporting under the Canadian Environmental Sustainability Indicators (CESI) initiative. Environment Canada and Statistics Canada. Retrieved on 17 December, 2013. Available from: http://publications.gc.ca/pub?id=381540&sl=0.
> e British Columbia Ministry of Environment (2000) Ambient water quality assessment and objectives for the Lower Columbia River: Birchbank to the US border. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/objectives/lowcolum/lowercolumbia.html#table1.
> Canadian Environmental Sustainability Indicators Page 18 of 32
> f Environment Canada (2005) Site-specific water quality guidelines for the Beaver River at Park Gate Highway 1 for the purpose of national reporting. Tri-Star Environmental Consulting.
> g Environment Canada (2005) Site-specific Water Quality Guidelines for the Kicking Horse River above Field, BC for the purpose of national reporting. Tri-Star Environmental Consulting.
> h Environment Canada (2005) Site-specific Water Quality Guidelines for the Kootenay River at Kootenay Crossing for the purpose of national reporting. Tri-Star Environmental Consulting. Retrieved on 17 December, 2013. Available from: http://waterquality.ec.gc.ca/WaterQualityWeb/PDFDocs/BC08NF0001%20- %20kootenay%20at%20kootenay%20crossing.pdf.
> i Environment Canada (2005) Site-specific Water Quality Guidelines for the Liard River at Upper Crossing for the Purpose of National Reporting. Tri-Star Environmental Consulting. Retrieved on 17 December, 2013.. Available from: http://waterquality.ec.gc.ca/WaterQualityWeb/PDFDocs/YT10AA0001%20- %20Liard%20at%20Upper%20Crossing.pdf.
> j Environment Canada (2005) Site-specific Water Quality Guidelines for the Skeena River at Usk for the purpose of national reporting. Tri-Star Environmental Consulting. Retrieved on 17 December, 2013.. Available from: http://waterquality.ec.gc.ca/WaterQualityWeb/PDFDocs/BC08EF0001%20- %20skeena%20at%20usk.pdf.
> k Swain LG (1990) Okanagan area, Similkameen River sub-basin water quality assessment and objectives. British Columbia Ministry of Environment. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/objectives/similkameen2/similkameen2.html#ccip.
> l British Columbia Ministry of Environment (1987) Water quality criteria for copper: Overview report. Retrieved on 3 August, 2011. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/copper/copper.html.
> m British Columbia Ministry of Water, Land and Air Protection (1997) Water quality assessment and objectives for the Fraser River from Moose Lake to Hope. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/objectives/frasermoose/Moosehopetech.pdf.
> n British Columbia Ministry of Water, Land and Air Protection (2004) Water quality assessment and objectives for the Elk River for the purpose of national reporting.
> o Warrington PD (1995) Ambient water quality criteria for fluoride. British Columbia Ministry of Environment. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/fluoride/index.html.
> p British Columbia Ministry of Environment (1987) Water quality criteria for lead: overview report. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/lead/lead.html.
> q Nagpal NK (2001) Ambient water quality guidelines for manganese: Overview report. British Columbia Ministry of Environment. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/manganese/manganese.html.
> r Environment Canada (2005) Site-specific Water Quality Guidelines for the Sumas River at the international boundary for the purpose of national reporting. Tri-Star Environmental Consulting. Retrieved on 17 December, 2013. Available from: http://waterquality.ec.gc.ca/WaterQualityWeb/PDFDocs/BC08MH0027%20-%20sumas.pdf.
> Canadian Environmental Sustainability Indicators Page 19 of 32
> s Nordin RN and Pommen LW (2001) Water quality criteria for nitrogen (nitrate, nitrite, and ammonia): Overview report. British Columbia Ministry of Environment and Parks. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/nitrogen/nitrogen.html.
> t British Columbia Ministry of Water, Land and Air Protection (1998) Water quality assessment and recommended objectives for the Salmon River. MacDonald Environmental Sciences Ltd. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/objectives/salmon/salmon.html.
> u Swain LG (1987) Takla-Nechako areas, Nechako River water quality assessment and objectives. British Columbia Ministry of Environment and Parks. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/objectives/nechako/nechako.html.
> v Ontario Ministry of the Environment and Energy (1994) Water management policies, guidelines, provincial water quality objectives. Retrieved on 17 December, 2013. Available from: https://archive.org/details/watermanagementp00ontauoft.
> w Nagpal NK (2001) Ambient water quality guidelines for selenium. British Columbia Ministry of Environment. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/selenium/selenium.htm.
> x British Columbia Ministry of Environment (1996) Ambient water quality criteria for silver. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/silver/silver.html.
> y British Columbia Ministry of Environment (2000) Ambient water quality guidelines for sulphate: Overview report. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/sulphate/sulphate.html.
> z British Columbia Ministry of Environment (2001) Water quality guidelines for temperature: Overview report. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/temptech/temperature.html#tab1.
> aa British Columbia Ministry of Environment (1999) Ambient water quality guidelines for zinc: Overview report. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/zinc/zinc.html.
> ab British Columbia Ministry of Environment (1997) Methods for deriving site-specific water quality objectives in British Columbia and Yukon. Retrieved on 17 December, 2013. Available from: http://www.env.gov.bc.ca/wat/wq/BCguidelines/effects_ratio/effectsratio.html.

**Comment by joethorley** [comment]
However lots SSG (site specific guidelines)

**Comment by joethorley** [comment]
We are down to 
Failed to substitute 'Ammonia', 'Barium', 'Chromium', 'Colour', 'Copper Dissolved', 'E. coli', 'Fecal coliforms', 'Oxygen Dissolved', 'Temperature' and 'Turbidity'.

**Comment by joethorley** [comment]
We should also add 
'NO2/NO3', 'NO2+NO3'

**Comment by stephhazlitt** [comment]
The [Working Water Quality Guidelines](http://www2.gov.bc.ca/assets/gov/environment/air-land-water/water/waterquality/wqgs-wqos/bc_env_working_water_quality_guidelines.pdf) from the BC Government website might be a resource for some of these parameters?

**Comment by joethorley** [comment]
We are now down to Failed to substitute 'Colour', 'E. coli', 'Fecal coliforms', 'Temperature' and 'Turbidity'.

**Comment by joethorley** [comment]
'Colour', 'E. coli', 'Fecal coliforms', 'Temperature' and 'Turbidity' are all variables with guidelines that depend on previous values. I'm closing this issue.
